### ISSUE TITLE
Crash (SIGSEGV) changing wallpaper during GIF extraction + KDE dbus-fallback bug (fixed)

### ISSUE THREAD

**Issue by ACFHarbinger** [ACFHarbinger/Image-Toolkit#648]
## Reported live

App crashed (SIGSEGV / signal 11, `python backend/main.py` exit code 139) while changing the wallpaper during a GIF extraction. After restart, the "change wallpaper" button silently did nothing on two attempts, though the system-display slideshow daemon *did* successfully change the wallpaper in the meantime.

## Fixed (commit `aa55b90b`)

Found and fixed a real, independent bug that explains the "button did nothing" symptom: `backend/src/core/wallpaper/_dbus.py::evaluate_kde_script_with_fallback` had a dead fallback path — its `except` block logged "trying dbus-python fallback" but then immediately re-raised the exception instead of ever calling `evaluate_kde_script_dbus_python()`. So whenever `base.evaluate_kde_script` failed for any reason (including the `AttributeError` seen live — `module 'base' has no attribute 'evaluate_kde_script'`, i.e. a stale/rebuilt `base` extension missing that symbol), the whole KDE desktop-enumeration and wallpaper-scripting path failed silently, `get_kde_desktops()` swallows the exception and returns an empty list, and per-desktop wallpaper application has nothing to act on even though the outer `WallpaperWorker` reports `Success: True` (it apparently still manages a "set for all desktops" KPackage-level call that doesn't depend on desktop enumeration).

Fix: removed the `raise exc from None`, letting execution correctly fall through to the dbus-python path as the docstring always claimed. 5 new regression tests added.

**Separate note:** the specific `AttributeError` in the user's log (`module 'base' has no attribute 'evaluate_kde_script'`) most likely means their currently-**installed** `base` native extension is stale relative to current source (the function exists in `base/src/core/wallpaper.cpp` / is bound in `bindings.cpp`) — not something this session's work touched or broke; rebuilding/reinstalling the `base` extension (`just build-base` or equivalent) should clear that specific error even without the dbus-fallback fix. The dbus-fallback fix makes the app resilient to *any* future recurrence of a similar failure regardless of cause.

## Not yet root-caused: the SIGSEGV crash itself

No Python traceback for the crash itself (native segfaults don't produce one) — only the trailing `BrokenPipeError` from a `SpawnPoolWorker` trying to write its result back through a pipe to a parent that had already died, which is a downstream symptom of the crash, not its cause.

Timing correlation worth investigating: the crash happened while (a) a `QueueExecutionWorker` parallel extraction Pool was active (the traceback names a `SpawnPoolWorker`, confirming the `spawn` multiprocessing context from #485's fork→spawn fix was in play) and (b) a wallpaper-change had just completed. Two hypotheses, neither confirmed:

1. An interaction between the GUI's Qt threads and the `spawn` multiprocessing context under load (spawning is a much heavier, more frequent operation per-task than fork was, given `maxtasksperchild=1`) — possibly exposed or introduced by #485's fork→spawn change.
2. A pre-existing crash class (this app has a documented history of off-thread QWidget-finalize crashes, #478/#480/#481) that fork's classic "only the forking thread survives in a multithreaded child" hazard could equally have caused before #485, just not yet observed.

**Needs**: a reproduction (ideally with `ulimit -c unlimited` so a core dump is captured) or a debug build with AddressSanitizer to actually pin down the faulting frame. Filing this issue mainly to record the correlation and get it on the board — not claiming a root cause without a real backtrace.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

**Comment by ACFHarbinger** [comment]
Confirmed via a second live log dump from the user — the currently-installed `base` extension is missing `evaluate_kde_script`, `set_wallpaper_gnome`, **and** `database` (`AttributeError: module 'base' has no attribute 'database'` when opening the Library Database tab). All three point to the same root cause: it's a stale build, predating all of these additions — not a code bug. Fix is `just build-base` to rebuild and reinstall the real extension the running app loads (distinct from the scratch `build/base/` directory this session's #471 Windows-build verification work has been using, which never touches the user's actual installed copy).

**Comment by ACFHarbinger** [comment]
Housekeeping: the dbus-fallback fix in `aa55b90b` is on `main`. Confirmed the 5 regression tests in `backend/test/image/test_wallpaper_kde_dbus_fallback.py` pass.

Closing this issue. The SIGSEGV itself was never given a Python traceback; if the live `AttributeError: module 'base' has no attribute 'evaluate_kde_script'` recurs, rebuild/reinstall the `base` extension (`just build-base` or equivalent) — that symbol exists in current source and a stale installed `.so` is the likely cause.

The dbus-fallback path now actually runs when `base.evaluate_kde_script` fails, so per-desktop KDE wallpaper application is no longer a silent no-op in that case.
