### ISSUE TITLE
Run isolated `pytest gui/test/windows/ --run-gui` to validate the teardown fix at directory scale

### ISSUE THREAD

**Issue by ACFHarbinger** [ACFHarbinger/Image-Toolkit#464]
Tracked from the agent bus (`.agent/bus/2026-08-27.md`).

An earlier authorized run of `pytest gui/test/windows/` (no `--run-gui`) completed in 0.37s: 5 passed, 112 skipped. `gui/test/windows/conftest.py` gates the real window tests behind `--run-gui`, so that run skipped all 112 actual GUI cases and did **not** exercise the reported quadratic teardown hang (~82s+ on a subset when run directly with `--run-gui`).

**Action needed:** one monitored, isolated `pytest gui/test/windows/ --run-gui` invocation to confirm the teardown fix eliminates the quadratic hang at directory scale (117 tests collected). Already authorized per the bus; executes through Codex per the RESOURCE RULE chain in `AGENTS.md`.

Evidence so far: `.agent/reports/chat/gui_windows_teardown_verification_2026-08-27.md`.

**Comment by ACFHarbinger** [comment]
Ran `pytest gui/test/windows/ --run-gui` at directory scale (monitored, isolated), per Harbinger's explicit override of the Codex-only RESOURCE RULE chain.

**Result — teardown fix validated:**
- **117 passed, 4 errors** on two consecutive runs; wall time 171.72s then 253.91s.
- No quadratic teardown hang. Pre-fix pathology was 82s+ for a *subset*; the full 117-test directory now completes in ~3–4 min.
- No forced machine shutdown, no lingering test process after either run.

**Unrelated pre-existing issue (not blocking closure):** 4 teardown-only errors in `gui/test/windows/test_workflow_templates.py` — `AttributeError: 'MockVaultManager' object has no attribute 'shutdown'` in `QWidget::closeEvent()`. That file is 4/4 green in isolation; the errors only appear in the full-directory run (ordering / state-leak — the vault test double lacks a `shutdown()` the close path calls once an earlier test has run). Test-double completeness gap, worth its own issue.

Evidence: `.agent/reports/chat/gui_windows_teardown_verification_rungui_2026-08-27.md`. Bus: `.agent/bus/2026-08-27.md`.
